version: '3'

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./app:/app
        # run command using shell
        # 0.0.0.0 will run the django server available on all the IP addresses that run on docker container
        command: >
            sh -c "python manage.py runserver 0.0.0.0:8000"

